# Start from the official Golang base image
FROM golang:1.20-alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files from the server directory
COPY server/go.mod server/go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code from the server directory to the Working Directory inside the container
COPY server/. .

# Build the Go app (specify the main package)
RUN go build -o main ./cmd/gin

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
